name : RLJMedia Website
brand : RLJMedia Creative Branding solutions
description : RLJMedia branding website
keyword : 
url : http://rljmedia.github.io
email : roger@rljmedia.com  
twitter : rljmedia
github : rljmedia
author : Daigo Fujiwara
analytics : UA-
year : 2015
markdown : kramdown
exclude :
  - node_modules
